export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const FETCH_POKEMONS = 'POKEMONS/FETCH_POKEMONS'
export const FETCH_POKEMONS_DETAILS = 'POKEMONS/FETCH_POKEMONS_DETAILS'
